### ISSUE TITLE
[/departments]

### ISSUE THREAD

**Issue by jcvsilva** [duo-dinamico/ServiceReports#53]
- [x] post
   - [x] Validar que casino existe
 - [x] patch
   - [x] Validar que casino existe
 - [x] delete
 - [x] get

**Comment by joaojesus81** [comment]
https://github.com/all-contributors please add @jcvsilva for tests, code and review pull requests

**Comment by joaojesus81** [comment]
@all-contributors please add @jcvsilva for code, tests, issues and review pull requests
